// Generated by scripts/sync-bunny-course.ts. Do not edit by hand.
// Maps a course slug to its lessons' Bunny Stream video GUIDs, by module/lesson index.

export type CourseVideoEntry = {
  m: number;
  l: number;
  videoId: string;
  title?: string;
};

export const courseVideos: Record<string, CourseVideoEntry[]> = {};
